version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
        exclude-patterns:
          - "super-linter/*"
          - "JackPlowman/reusable-workflows/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      typescript:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "dashboard"
    commit-message:
      prefix: "deps(python-tests)"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      uv:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
