version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
