jobs:
  check-pull-request-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Title
      uses: deepakputhraya/action-pr-title@v1.0.2
      with: {allowed_prefixes: 'feat: ,fix: ,bug: ,ci: ,refactor: ,docs: ,build: ,chore(,deps(,chore:
          ,feat!: ,fix!: ,refactor!: ,test: '}
  labeller:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Label Pull Request
      uses: actions/labeler@v5.0.0
      with: {configuration-path: .github/other-configurations/labeller.yml, repo-token: '${{
          secrets.GITHUB_TOKEN }}', sync-labels: true}
    - env: {GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'}
      name: Add Size Labels
      uses: pascalgn/size-label-action@v0.5.5
      with: {sizes: "{\n  \"0\": \"XS\",\n  \"40\": \"S\",\n  \"100\": \"M\",\n  \"\
          200\": \"L\",\n  \"800\": \"XL\",\n  \"2000\": \"XXL\"\n}\n"}
name: Pull Request Checks
on:
  pull_request:
    types: [opened, edited, unlocked, labeled, synchronize, reopened, ready_for_review]
permissions: {pull-requests: write}
